name: cpu-tests

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -e .

    - name: Test with unittest
      run: |
        python -m unittest -k CPU
    - name: Test cpu inference
      run: |
        python -m unittest -k knee_itk
