name: sphinx-build

on:
  pull_request:
  push:
    branches: master

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -e .
        pip install sphinx

    - name: Build docs
      working-directory: docs
      run: |
        make html SPHINXOPTS="-W --keep-going -n" 
